In [ ]:
"""
1] In the below elements which of them are values or an expression? eg:- values can be
   integer or string and expressions will be mathematical operators.
   *
   hello
   -87.8
   -
   /
   +
   6
   
   values        : 'hello', -87.8, 6
   Expressions   : * - / + 6
   
"""

In [ ]:
"""
2] What is the difference between string and variable?

Ans:
        Variable : @ We store different types of values in variable. 
        
                   @ Variable is the name of the computer memory location.
                   
                   @ Naming conventions are being followed by variables:
                       * Variable name cannot start with number.
                       * Variable name can start with (A-Z) or (a-z) or (_)
                       
                   @ In python, we don't need to create variable separately, we can create directly by assigning value to it.
                   
          String : @ string is a collection of character.
                   @ In python, we don't have separate data type for character
                     it is considered in string with one length.
                   @ We have to mention string name inside single or double quotes.
                   @ String is Immutable.
                   @ To see the range of string, we use slicing method.


"""

In [ ]:
"""
3] Describe three different data types.
      
           Numbers :

            @ Integer : Integer (int) is the numeric data type. Integer contains positive or negative number but not decimal.
            
            @ Float   : Float is the number which contain decimal point.
            
            @ Complex 
              Number  : It is the type where real and imaginary numbers are mixed. for ex :- 1+2j
              

     Sequence type : 
      
            @ String : It is the collection of characters. string are enlosed within single or double quotes.
                       String is an immutable. 
                       
            @ Tuple  : Tuple is a collection of different data types enloclosed within paranthesis. ex : ('shivani', 234)
                       Tuple is immutable and ordered data type.           
                       
            @ List   : List is same as the Tuple and enclosed within square brackets. ex : [2,34,'shivani',7+3j]
                       List is mutable.
                       
     Mapping Type : 
             
                       Dictionary data type is the collection of different data types but with the key-value pairs.
                       It is ordered data type
                       Dictiory is mutable.
                       ex : {'key1' : 1, 'key2' : 2, 'key3' : 3}

"""

In [ ]:
"""
4]  What is an expression made up of? What do all expressions do?

    Expressions : Combination of operator and operand is know as Expression.
    
    There are different types of expressions as given below :
        
        @ Arithmetic Expressions : In this type of expression we make use of numbers (like integer,
                                   floating point) along with Arithmetic operators  ( + - * / % ).
                                   Ex : (5+2), (4*3), (5%4)
        
        @ String Expressions     : In String Expression, we do concatenation (to combine two strings),
                                   replication (to make repitition of a string a number of times).
                                   Ex : "string"*2 (o/p : stringstring) , 
                                   "string"+"Lite" (o/p : stringLite).
                                   
        @ Relational Expression  : We make use of relational operators in together with literals or 
                                   variable is known as relational Expression.    
                                   Relational operators : <  >  >= <= 
                                   Ex : (a+3) >= (a*2).
                                   
        @ Logical Expressionss   : Logical Operator (and , or) are being used in logical expressions.
                                   Whenever we want need to check statements as true or false we 
                                   make use of this expression.
                                   Ex : a = 10                   |   (5==3)||(5>3)
                                        b = 9                    |   o/p : True
                                        c = (a==10)and(b<=10)    |
                                        print(c)                 | 
                                  o/p : True                     |
                                                                
   


"""

In [ ]:
"""
5]  This assignment statements, like spam = 10. What is the difference between an expression and a statement?

Ans:    spam = 1o is a statement as well as exprression. Statement is a line or piece of code. ex: If statement
        looping or printing a value, etc.whereas Expression is a combination of operators and operands.
        Every Expression can be statement but not vice versa.
         

"""

In [ ]:
"""
6] After running the following code, what does the variable bacon contain?
   bacon = 22
   bacon + 1
   
A    After running the code bacon's value will get increased by 1.
     and Varibale bacon will contain 23.


"""

In [ ]:
"""
7] What should the values of the following two terms be?
   'spam' + 'spamspam'
   'spam' * 3
   
Ans : 'spam' + 'spamspam':- spamspamspam
     'spam' * 3         :- spamspamspam




"""

In [ ]:
"""
8. Why is eggs a valid variable name while 100 is invalid?

Ans : Because Varibale names cannot start with number.

"""

In [ ]:
"""
9. What three functions can be used to get the integer, floating-point number, or string version of a value?

Ans :   
                       To get the integer : int(input())
                       To get the String  : input()
            To get the Floating point no. : float(input())

"""

In [ ]:
"""
10]  Why does this expression cause an error? How can you fix it? 'I have eaten ' + 99 + ' burritos.'

Ans : This expression cause an error because 99 is an integer. String cannot be concatenated with integers. To 
       fix this bug we can enclose 99 within quotatiion marks i.e.  'I have eaten ' + '99' + ' burritos.'



"""